# Generated by Django 4.1.7 on 2023-03-12 08:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryseries',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='categoryseries',
            name='description',
        ),
        migrations.RemoveField(
            model_name='categoryseries',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='subcategorymovie',
            name='cast',
        ),
        migrations.RemoveField(
            model_name='subcategorymovie',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subcategorymovie',
            name='title',
        ),
        migrations.AddField(
            model_name='detailmovie',
            name='cast',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailmovie',
            name='description',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailmovie',
            name='poster',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailmovie',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailseries',
            name='cast',
            field=models.CharField(default=django.utils.timezone.now, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailseries',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailseries',
            name='poster',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detailseries',
            name='title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
