# Generated by Django 4.1.7 on 2023-03-12 08:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0002_remove_categoryseries_cast_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryseries',
            name='poster',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
