# Generated by Django 4.1.7 on 2023-03-13 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0004_subcategorymovie_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=2000)),
                ('photos', models.CharField(max_length=2000)),
                ('items', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.shop')),
            ],
        ),
        migrations.RemoveField(
            model_name='detailshop',
            name='add',
        ),
        migrations.DeleteModel(
            name='CategoryShop',
        ),
        migrations.DeleteModel(
            name='DetailShop',
        ),
    ]
