# Generated by Django 4.1.7 on 2023-03-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0006_rename_photos_shop_cover_rename_items_shop_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='stock',
        ),
    ]
