# Generated by Django 4.1.7 on 2023-03-13 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0007_remove_shop_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarvelHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('images', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='MarvelVillain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('images', models.CharField(blank=True, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='DetailChar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('story', models.TextField(blank=True)),
                ('multiverse', models.CharField(blank=True, max_length=300)),
                ('images', models.CharField(blank=True, max_length=300)),
                ('char_heroes', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelheroes')),
                ('char_villain', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelvillain')),
            ],
        ),
    ]
