# Generated by Django 4.1.7 on 2023-03-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0009_alter_detailchar_char_heroes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailHeroes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('story', models.TextField(blank=True)),
                ('multiverse', models.CharField(blank=True, max_length=300)),
                ('images', models.CharField(blank=True, max_length=300)),
                ('char_heroes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelheroes')),
            ],
        ),
        migrations.CreateModel(
            name='DetailVillain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300)),
                ('story', models.TextField(blank=True)),
                ('multiverse', models.CharField(blank=True, max_length=300)),
                ('images', models.CharField(blank=True, max_length=300)),
                ('char_villain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelvillain')),
            ],
        ),
        migrations.DeleteModel(
            name='DetailChar',
        ),
    ]
