# Generated by Django 4.1.7 on 2023-03-13 14:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0010_detailheroes_detailvillain_delete_detailchar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailheroes',
            name='char_heroes',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelheroes'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detailvillain',
            name='char_villain',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelvillain'),
            preserve_default=False,
        ),
    ]
