# Generated by Django 4.1.7 on 2023-03-13 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0012_alter_detailheroes_char_heroes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marvelheroes',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelheroes'),
        ),
        migrations.AddField(
            model_name='marvelvillain',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelvillain'),
        ),
        migrations.AlterField(
            model_name='detailheroes',
            name='char_heroes',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelheroes'),
        ),
        migrations.AlterField(
            model_name='detailvillain',
            name='char_villain',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.marvelvillain'),
        ),
    ]
