# Generated by Django 4.1.7 on 2023-03-22 12:33

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0013_marvelheroes_parent_marvelvillain_parent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300)),
                ('thumbnail', models.CharField(max_length=2000)),
                ('videos', models.CharField(max_length=2000)),
                ('childs', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='djangoapp.episode')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=2000)),
                ('total_season', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='series', to='djangoapp.series')),
            ],
        ),
        migrations.RemoveField(
            model_name='detailseries',
            name='uploads',
        ),
        migrations.RemoveField(
            model_name='subcategoryseries',
            name='child',
        ),
        migrations.DeleteModel(
            name='CategorySeries',
        ),
        migrations.DeleteModel(
            name='DetailSeries',
        ),
        migrations.DeleteModel(
            name='SubCategorySeries',
        ),
        migrations.AddField(
            model_name='season',
            name='child',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.series'),
        ),
        migrations.AddField(
            model_name='season',
            name='episode',
            field=models.ManyToManyField(to='djangoapp.episode'),
        ),
    ]
