# Generated by Django 4.1.7 on 2023-03-22 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0014_episode_season_series_remove_detailseries_uploads_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='season',
            old_name='child',
            new_name='series',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='childs',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='videos',
        ),
        migrations.RemoveField(
            model_name='season',
            name='episode',
        ),
        migrations.AddField(
            model_name='episode',
            name='episode',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoapp.season'),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
