# Generated by Django 4.1.7 on 2023-03-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0015_rename_child_season_series_remove_episode_childs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='thumbnail',
            field=models.CharField(default=1, max_length=2000),
            preserve_default=False,
        ),
    ]
