# Generated by Django 4.1.7 on 2023-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0017_episode_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='cast',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
