# Generated by Django 4.1.7 on 2023-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0019_series_total_episode_alter_series_cast'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='title',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
