# Generated by Django 4.1.7 on 2023-03-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0022_remove_series_total_episode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='release',
        ),
    ]
