# Generated by Django 4.1.7 on 2023-04-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0025_alter_detailmovie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymovie',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
