# Generated by Django 4.1.7 on 2023-04-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0026_subcategorymovie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='series',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='thumbnail',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='videos',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='cast',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='series',
            name='imdb_rating',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='series',
            name='release',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='series',
            name='rotten_rating',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='series',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
