# Generated by Django 4.1.7 on 2023-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0029_categorymovie_imdb_rating_categorymovie_resolution_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categorymovie',
            name='imdb_rating',
        ),
        migrations.RemoveField(
            model_name='categorymovie',
            name='resolution',
        ),
        migrations.RemoveField(
            model_name='categorymovie',
            name='rotten_rating',
        ),
        migrations.AddField(
            model_name='subcategorymovie',
            name='imdb_rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorymovie',
            name='resolution',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorymovie',
            name='rotten_rating',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
