# Generated by Django 4.1.7 on 2023-04-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0030_remove_categorymovie_imdb_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='num_season',
            field=models.CharField(default=1, max_length=11),
            preserve_default=False,
        ),
    ]
