# Generated by Django 4.1.7 on 2023-04-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0031_series_num_season'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='season',
            new_name='tag_season',
        ),
        migrations.RenameField(
            model_name='season',
            old_name='series',
            new_name='tag_series',
        ),
        migrations.RemoveField(
            model_name='season',
            name='name',
        ),
        migrations.RemoveField(
            model_name='season',
            name='title',
        ),
        migrations.AddField(
            model_name='episode',
            name='tmdb_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='season',
            name='season',
            field=models.IntegerField(),
        ),
    ]
