# Generated by Django 4.1.7 on 2023-04-14 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0032_rename_season_episode_tag_season_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
