# Generated by Django 4.1.7 on 2023-04-14 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0033_episode_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
    ]
