# Generated by Django 4.1.7 on 2023-04-14 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0034_remove_episode_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='season',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
