# Generated by Django 4.1.7 on 2023-04-15 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0035_episode_season'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='title',
        ),
    ]
