# Generated by Django 4.1.7 on 2023-05-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0038_alter_episode_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='name3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='series',
            name='name4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
