# Generated by Django 4.1.7 on 2023-05-13 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0039_series_name1_series_name2_series_name3_series_name4'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='name5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
