# Generated by Django 4.1.7 on 2023-05-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0040_series_name5'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymovie',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
