# Generated by Django 4.1.7 on 2023-05-13 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0041_subcategorymovie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorymovie',
            name='slug_name',
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
