# Generated by Django 4.1.7 on 2023-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0043_remove_subcategorymovie_slug_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategorycomic',
            name='cover_artist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='name1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='name2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='name3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='name4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='name5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='penciller',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='published',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategorycomic',
            name='writer',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
