# Generated by Django 4.1.7 on 2023-05-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0044_subcategorycomic_cover_artist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategorycomic',
            name='cover_artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategorycomic',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='subcategorycomic',
            name='penciller',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
